name: dhondhu-workflow

on:
  push:
    branches:
      - main
      - feature/**

jobs:
  meraphela_workflow:
    name: dhondhu_maraj
    runs-on: self-hosted   # ðŸ‘ˆ yeh tumhare machine wale runner ko use karega
    steps:
      - name: dhondhu_maraj print
        run: echo "hello maraj"


